openapi: 3.0.2
info:
  title: rails-api-boilerplate
  description: This is rails-api-boilerplate API
  version: 1.0.0
security:
  - Bearer: []
servers:
  - url: "http://localhost:8080/api/v1"
tags:
  - name: projects
  - name: users
paths:
  /projects:
    get:
      tags:
        - projects
      summary: Get all projects.
      description: Returns an array of Project model
      parameters: []
      responses:
        '200':
          description: A JSON array of Project model
          content:
            application/json:
              schema:
                type: object
                required:
                  - projects
                properties:
                  projects:
                    type: array
                    items:
                      type: object
                      required:
                        - project
                      properties:
                        project:
                          type: object
                          required:
                            - id
                            - name
                            - description
                            - is_archived
                            - created_at
                            - updated_at
                          properties:
                            id:
                              type: integer
                            name:
                              type: string
                            description:
                              type: string
                            is_archived:
                              type: boolean
                            created_at:
                              type: string
                            updated_at:
                              type: string
                example:
                  projects:
                    - project:
                        id: 1
                        name: "Hartmann Group Project No.1"
                        description: "This is Hartmann Group Project No.1"
                        is_archived: false
                        created_at: "2020-10-05T05:02:03.369+09:00"
                        updated_at: "2020-10-05T05:02:03.369+09:00"
                    - project:
                        id: 2
                        name: "Hartmann Group Project No.2"
                        description: "This is Hartmann Group Project No.2"
                        is_archived: false
                        created_at: "2020-10-06T04:12:03.572+09:00"
                        updated_at: "2020-10-07T10:12:03.684+09:00"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
              example:
                errors:
                  - "Not Authenticated"
  /users:
    post:
      tags:
        - users
      summary: Create a user.
      description: Creates a user and Returns user's auth token
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  description: user's email
                  type: string
                password:
                  description: user's password
                  type: string
              required:
                - email
                - password
              type: object
            example:
              email: sample@email.com
              password: password
      parameters: []
      responses:
        '200':
          description: A JSON user's auth token
          content:
            application/json:
              schema:
                type: object
                properties:
                  auth_token:
                    type: string
              example:
                auth_token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMDIsImV4cCI6MTYwMzU1OTMzMn0.o_RZeJxzJTcdN30PmxpH6zd0BrUvn477pTQCfaoYZOE
  /users/authenticate:
    post:
      tags:
        - users
      summary: Authenticate a user.
      description: Authenticate a user and Returns user's auth token
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  description: user's email
                  type: string
                password:
                  description: user's password
                  type: string
              required:
                - email
                - password
              type: object
            example:
              email: sample@email.com
              password: password
      responses:
        '200':
          description: A JSON user's auth token
          content:
            application/json:
              schema:
                type: object
                properties:
                  auth_token:
                    type: string
              example:
                auth_token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMDIsImV4cCI6MTYwMzU1OTMzMn0.o_RZeJxzJTcdN30PmxpH6zd0BrUvn477pTQCfaoYZOE
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
              example:
                errors:
                  - "Invalid email/password"
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: Credentials or access token for API
